name: Build and test matrix

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-2022,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cc: "gcc-10", cxx: "g++-10"
          }
        - {
            name: "Ubuntu Latest Clang",
            os: ubuntu-latest,
            cc: "clang-12", cxx: "clang++-12"
          }
    steps:
      - uses: actions/checkout@v1
      - name: "Configure"
        run: cmake -S . -B build
        env:
          CC: ${{{ matrix.config.cc }}
          CXX: ${{{ matrix.config.cxx }}
      - run: cmake --build build
      - run: cd build
      - run: ctest --extra-verbose
