name: Build and test matrix

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
               name: "Windows Latest MSVC"
               os: windows-2022
               cc: "cl", cxx: "cl"
               environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            }
          - {
               name: "Ubuntu Latest GCC", artifact: "Linux.7z",
               os: ubuntu-latest,
               cc: "gcc-10", cxx: "g++-10"
            }
          - {
               name: "macOS Latest Clang", artifact: "macOS.7z",
               os: macos-latest,
               cc: "clang-12", cxx: "clang++-12"
            }
    steps:
      - uses: actions/checkout@v1
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: cd build
      - run: ctest --extra-verbose
